name: Trigger Orchestrator Agent on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-azure-function:
    runs-on: ubuntu-latest
    steps:
      - name: Log PR Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Commit ID: ${{ github.event.pull_request.head.sha }}"

      - name: Call Orchestrator Agent Azure Function
        run: |
          REPO_NAME=${{ github.repository }}
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          ORCHESTRATOR_AGENT_URL="https://agents-affggrfheabwf0cm.southindia-01.azurewebsites.net/api/orchestrator_agent"
          echo "Triggering orchestrator agent for repo: $REPO_NAME, commit: $COMMIT_ID"
          RESPONSE=$(curl -s -w '\n%{http_code}' -X POST "$ORCHESTRATOR_AGENT_URL" \
            -H "Content-Type: application/json" \
            -d '{"repository": "'$REPO_NAME'", "commit": "'$COMMIT_ID'"}')
          HTTP_BODY=$(echo "$RESPONSE" | head -n -1)
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          echo "Orchestrator agent response status: $HTTP_STATUS"
          echo "Orchestrator agent response body: $HTTP_BODY"
