name: Trigger Orchestrator Agent on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-azure-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Orchestrator Agent Azure Function
        env:
          AZURE_FUNCTION_URL: ${{ secrets.ORCHESTRATOR_AGENT_URL }}
        run: |
          REPO_NAME=${{ github.repository }}
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          echo "Triggering orchestrator agent for repo: $REPO_NAME, commit: $COMMIT_ID"
          curl -X POST "$AZURE_FUNCTION_URL" \
            -H "Content-Type: application/json" \
            -d '{"repository": "'$REPO_NAME'", "commit": "'$COMMIT_ID'"}'
