name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci-cd.yml'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn clean install
      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-logs
          path: backend/target/surefire-reports/*.txt
      - name: Archive full Maven log
        if: always()
        shell: powershell
        run: |
          try {
            Copy-Item ./target/surefire-reports/*.txt backend/maven.log -ErrorAction Stop
          } catch {
            Write-Host 'No test logs found, skipping.'
          }
      - name: Upload full Maven log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-maven-log
          path: ./maven.log
      - name: Show Maven log
        if: always()
        shell: powershell
        run: |
          if (Test-Path ./maven.log) {
            Get-Content ./maven.log
          } else {
            Write-Host 'No log found.'
          }
      - name: Upload Spring Boot JAR
        uses: actions/upload-artifact@v4
        with:
          name: demo-0.0.1-SNAPSHOT
          path: ./target/*.jar

  deploy:
    needs: build
    runs-on: [self-hosted, windows]
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        shell: cmd
    steps:
      - name: Download Spring Boot JAR
        uses: actions/download-artifact@v4
        with:
          name: demo-0.0.1-SNAPSHOT
          path: C:/Users/devops_agentic/Desktop/DeployApp
      - name: Stop existing Spring Boot app
        run: |
          for /f "tokens=2" %%a in ('tasklist ^| findstr java.exe') do taskkill /F /PID %%a
          if %ERRORLEVEL% NEQ 0 echo No running Java process found or stopped. & exit /b 0
      - name: Start Spring Boot app
        run: |
          cd /d C:\Users\devops_agentic\Desktop\DeployApp
          java -jar demo-0.0.1-SNAPSHOT.jar

  test-app:
    needs: deploy
    runs-on: [self-hosted, windows]
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        shell: cmd
    steps:
      - name: Test if Spring Boot app is running
        run: |
          timeout /t 10
          curl -s -o nul -w "%{{http_code}}" http://localhost:8080/actuator/health | find "200" >nul && echo Spring Boot app is up and running. || (echo Spring Boot app is not reachable. & exit 1)
